### ISSUE TITLE
Endpoint bug for getURL APIs in dev env and prod nev

### ISSUE THREAD

**Issue by seriouszyx** [casdoor/casdoor-go-sdk#11]
When developing with Casdoor's sdk, I ran into problems. In **dev** env, the links generated by getURL APIs are set as **http://localhost:8000** instead of  **http://localhost:7001**. Maybe we should provide a param for dev or prod and a configuration for the link to Casdoor login page in dev env. Or some better solutions.

**Comment by hsluoyz** [comment]
@seriouszyx I don't think this is an issue. See: https://casdoor.org/docs/basic/server-installation#development-mode
