### ISSUE TITLE
[Feature] How to getAccessToken without ui and with usersname and password using casdoor-go-sdk?

### ISSUE THREAD

**Issue by radiorz** [casdoor/casdoor-go-sdk#112]
references:
https://casdoor.org/docs/how-to-connect/oauth/#resource-owner-password-credentials-grant

good to have  this api in casdoor-go-sdk❤

**Comment by hsluoyz** [comment]
@radiorz it's not part of this SDK. You should use a OAuth 2.0 library which supports `Resource Owner Password Credentials Grant` to do this
