### ISSUE TITLE
sdk   client.RefreshOAuthToken,  without set scope

### ISSUE THREAD

**Issue by Y-Matin** [casdoor/casdoor-go-sdk#116]
first :  get token by code and  state  , and set scope:profile

when refresh token  by  client.RefreshOAuthToken,   get new accessToken  without scope .
so  I use new accessToken to get userinfo (/api/userinfo)， get response doesn't  have  user's permissions.

but the resultful api  need  scope  parameter
![image](https://github.com/casdoor/casdoor-go-sdk/assets/28671733/db288a8c-d93d-49af-bf53-40a30c1e606e)

**Comment by Y-Matin** [comment]
Can you tell me first if this is a problem or if my usage is incorrect ？ Thanks

**Comment by CRSylar** [comment]
i've actually the same problem, when calling client.RefreshOauthToken with the refresh token value i receive an error stating that the token  is invalid

**Comment by hsluoyz** [comment]
@Y-Matin @CRSylar can you make a PR?

**Comment by hsluoyz** [comment]
Closed as stale
