### ISSUE TITLE
GetGroups() API does not work

### ISSUE THREAD

**Issue by maknahar** [casdoor/casdoor-go-sdk#118]
There is a bug in GetGroups() function of this SDK. `get-group` API return elements like below:

```

       {

            "owner": "built-in",

            "name": "Finance",

            "createdTime": "2024-07-08T18:02:39+05:30",

            "updatedTime": "2024-07-08T18:02:39+05:30",

            "displayName": "FinanceOrg",

            "manager": "",

            "contactEmail": "",

            "type": "Virtual",

            "parentId": "built-in",

            "isTopGroup": true,

            "users": [

                "built-in/user_i8dbib"

            ],

            "isEnabled": true

        }

```
 
Users array here is a string. However SDK is assuming to it to be full user info struct. Resulting in following error:
 
> json: cannot unmarshal string into Go struct field Group.users of type casdoorsdk.User
 
Relevant code here: https://github.com/casdoor/casdoor-go-sdk/blob/master/casdoorsdk/group.go#L36
 
Please change the response type of the function to make the API work. Please let me know if you would like me to raise the PR.

casdoor-go-sdk/casdoorsdk/group.go at master · casdoor/casdoor-go-sdk
Go client SDK for Casdoor. Contribute to casdoor/casdoor-go-sdk development by creating an account on GitHub.

**Comment by hsluoyz** [comment]
@maknahar can you make a PR to fix it?

**Comment by maknahar** [comment]
Sure @hsluoyz

**Comment by maknahar** [comment]
@hsluoyz Looks like This commit https://github.com/casdoor/casdoor-go-sdk/commit/0b220df23128ccbc1498dc0bcdb94c9da2ca5122 from last week already fixes the issue. I will Close this bug.
