### ISSUE TITLE
Delete Token problem with "name" parameter 

### ISSUE THREAD

**Issue by DenisBytes** [casdoor/casdoor-go-sdk#124]
Version: v0.47.0

This is not really an issue but more of a suggestion.

When calling the method:

casdoorsdk.GetToken(name string)

it requires the JWT ID (ex. of a JWT ID, "admin/07ed1609-80e0-4dac-8a2c-e2dbbbac85c3")

But if you pass the full string just like the example it returns:

"invalid character '<' looking for beginning of value"

Looking into the method definition i found why it gave an error:

![image](https://github.com/user-attachments/assets/ad7ffb76-af2d-48f7-852a-961a2a785916)

Is that the method does the formatting itself. I haven't tried other the GetX methods but i suppose they do it where needed.

Quick Solution is to use the path.Base() standard library method:

![image](https://github.com/user-attachments/assets/ad04b06e-641e-4a61-9c4d-69ea81c1fbc3)

But it's better if there's documentation above the method

**Comment by hsluoyz** [comment]
@DenisBytes what do you pass? What got and what to expect?

**Comment by DenisBytes** [comment]
The full text.
"admin/07ed1609-80e0-4dac-8a2c-e2dbbbac85c3"
but instead it just requires.
"07ed1609-80e0-4dac-8a2c-e2dbbbac85c3".

As i said it's just a suggestion not really an issue.

Just add documentation

**Comment by hsluoyz** [comment]
No much need to add docs, all APIs are like that. People need to adapt themselves to use Casdoor SDK
