### ISSUE TITLE
How to set organization dynamically?

### ISSUE THREAD

**Issue by maknahar** [casdoor/casdoor-go-sdk#125]
I am using shared application feature of casdoor as describe here: https://casdoor.org/docs/application/shared-application/

This means organization to use will vary from one method to another method call and I cannot set the organization name in the SDK initialization. Is there a way to set the organization for one method call alone? 

For example instead of calling `casdoorClient.GetUsers()` method, I would like to have `casdoorClient.ForOrg(orgName).GetUsers()` or `casdoorClient.GetUsers(orgName)`. Does SDK currently support this use case?

**Comment by maknahar** [comment]
Hi,

It would be nice this issue seems valid to you and functionality is not available yet in SDK. Would be happy to raise the PR.

**Comment by hsluoyz** [comment]
@maknahar you should create new client with new org

**Comment by maknahar** [comment]
@hsluoyz Okay. Asking SDK users to create new client every time they make method call seems a bit excessive. But it make sense considering it is a breaking change.
