### ISSUE TITLE
Add user key

### ISSUE THREAD

**Issue by hamidrabedi** [casdoor/casdoor-go-sdk#140]
Add function to add user keys for user:

https://github.com/casdoor/casdoor/blob/master/controllers/user.go#L650

**Comment by hsluoyz** [comment]
@hamidrabedi can you make a PR to add it?

**Comment by hamidrabedi** [comment]
@hsluoyz i'm not sure how to do this one

**Comment by hsluoyz** [comment]
Call UpdateUser API
