### ISSUE TITLE
client.GetToken should not concat "name" input with "admin/" to get token id

### ISSUE THREAD

**Issue by punyaikhwan** [casdoor/casdoor-go-sdk#144]
JWT Claims produced by Casdoor already has prefix "admin/" for the jti field. So, it is not necessary to add prefix "admin/" to get token in function client.GetToken.

Sample of JWT Claims:
![image](https://github.com/user-attachments/assets/04d3cadb-1690-43ec-8977-8207c0a0f18f)

Current client.GetToken function:
![image](https://github.com/user-attachments/assets/00bd39a4-1cfa-49df-a9cb-6db8395f0dc7)

It will be a problem if we directly use claims.ID for function client.GetToken. The queried id will be `admin/admin/<jwtid>` that will cause error:
```
{
  "error": "GetOwnerAndNameFromId() error, wrong token count for ID: admin/admin/<jwtid>"
}
```

Additional info:
SDK version: v1.3.0
Casdoor version: [v1.774.0](https://github.com/casdoor/casdoor/tree/v1.774.0)

**Comment by hsluoyz** [comment]
@punyaikhwan name is not jti. 

https://door.casdoor.com/api/get-token?id=admin/60cf93b0-e885-420d-b383-6f4e3c004fe8
