### ISSUE TITLE
GetUser() bug, cannot parse response

### ISSUE THREAD

**Issue by xqbumu** [casdoor/casdoor-go-sdk#23]
use GetUser method to get details of the user, and Casdoor returns the content as follows

```
{
  "owner": "org-xxx",
  "name": "xxxxxx",
  "createdTime": ""
  ...
}
```
but in https://github.com/casdoor/casdoor-go-sdk/blob/eb61888a1f987f8be3e1eb1102e47239981bb65c/auth/base.go#L62

The returned content will be Unmarshal to auth.Response first, which is inconsistent with the json format returned by Casdoor, so the user details cannot be actually obtained from GetUser.

casdoor version: v1.45.0
casdoor-go-sdk version: v0.4.0

**Comment by hsluoyz** [comment]
@xqbumu plz change all texts into English
