### ISSUE TITLE
Missing SDK functionality - /api/set-password

### ISSUE THREAD

**Issue by Thambolo** [casdoor/casdoor-go-sdk#37]
Hi maintainers,

I need the /api/set-password function from the SDK. I would appreciate it a lot if you could help me add it in! It should allow empty "oldPassword".
side note: is there a chance for you to add a flexible function to send http POST requests, similar to how the SDK has DoGetBytesRaw for http GET requests to the casdoor server.

**Comment by hsluoyz** [comment]
@qianxi0410

**Comment by Thambolo** [comment]
@hsluoyz @qianxi0410 Greatly appreciated, thank you guys for the quick work 👍🏼
