### ISSUE TITLE
[question] how to logout with sdk

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor-go-sdk#59]
how to logout with sdk, it seems to be missing.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/22713311/229056471-fee40b4f-8b12-42cd-9593-40b324198d7a.png">

**Comment by hsluoyz** [comment]
@shiningstarts the OAuth is mainly for login. Logout is performed by your own application. So there's no SDK function to do this.
