### ISSUE TITLE
Unmarshal error while parsing wrong answer from casdoor

### ISSUE THREAD

**Issue by hound672** [casdoor/casdoor-go-sdk#60]
Hello!

I receive `unmarshal` error while I getting not json response from casdoor service.
For example:
```golang
	users, err := casdoorsdk.GetUsers()
	if err != nil {
		log.Fatalf("get users: %v", err)  // get users: invalid character '<' looking for beginning of value
	}
```

Why casdoor answered like that is an another question :)
But, I'd like to get from casdoor sdk more specific error, for instance: `ErrCasdoorInternal`.
In that case I will be able to write errors checking like that:
```golang
users, err := casdoorsdk.GetUsers()
if errors.Is(err, ErrCasdoorInternal) {
   // 
}
```

If you don't mind I'd make PR for fixing that.

**Comment by hsluoyz** [comment]
@hound672 PR is welcome!

**Comment by hound672** [comment]
Ok!
A question about implementation.
I noticed that every casdoor's public method (such as GetUserByUserId, GetUsers and so on) contains:
```golang
	err = json.Unmarshal(bytes, &user)
	if err != nil {
		return nil, err
	}
```
After: `bytes, err := DoGetBytesRaw(url)`

I thought to add helper for that in `util.go`. That helper will receive bytes and `interface{}` and if there is unmarshal error returns `ErrCasdoorInternal`.
So I need to replace in every method `err = json.Unmarshal(bytes, &user)` to this helper.
What do think?

**Comment by hsluoyz** [comment]
@hound672 sounds good.

**Comment by hsluoyz** [comment]
Doesn't seem to be an issue and the PR is mostly meaningless
