### ISSUE TITLE
[Enhancement] It will be more clear if have example code in this sdk

### ISSUE THREAD

**Issue by thanhtinhpas1** [casdoor/casdoor-go-sdk#68]

**Comment by hsluoyz** [comment]
@thanhtinhpas1 can you add some Go tests as example code?

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 can you add some Go tests as example code?

Okay, will do it.

**Comment by hsluoyz** [comment]
You can use example code here: https://casdoor.org/docs/how-to-connect/sdk#:~:text=casdoor%2Dgo%2Dsdk-,Casnode%2C%20Casbin%2DOA%2C%20Confita,-Java%20SDK
