### ISSUE TITLE
Unable to unmarshal response data after Casdoor using RespnseOk 

### ISSUE THREAD

**Issue by WinterOfBit** [casdoor/casdoor-go-sdk#71]
after https://github.com/casdoor/casdoor/commit/a6f803aff1e634ae92b669975baa366a6b3b39c8, casdoor-go-sdk codes like
```go
func GetUser(name string) (*User, error) {
	queryMap := map[string]string{
		"id": fmt.Sprintf("%s/%s", authConfig.OrganizationName, name),
	}

	url := GetUrl("get-user", queryMap)

	bytes, err := DoGetBytesRaw(url)
	if err != nil {
		return nil, err
	}

	var user *User
	err = json.Unmarshal(bytes, &user)
	if err != nil {
		return nil, err
	}
	return user, nil
}
```
No longer works (return empty struct / panic) because response format has changed from data model alone to wrapped response json. Take the user.go#GetUser() above as example. 

#### Before https://github.com/casdoor/casdoor/commit/a6f803aff1e634ae92b669975baa366a6b3b39c8 `/api/get-user` returns just user modal. 
<img width="952" alt="image" src="https://github.com/casdoor/casdoor-go-sdk/assets/68735689/25ef90db-6dcb-4c62-9b3d-1755c3c4dcf0">

#### Then after it returns standard reponse modal in which user modal is wrapped in `data` field.
<img width="856" alt="image" src="https://github.com/casdoor/casdoor-go-sdk/assets/68735689/a3a8add0-26ce-4cbe-889a-6db3ec67b431">

Quite a lot apis in casdoor-go-sdk has been influenced, such as user.go, resource.go...... Almost anywhere code like
```go
bytes, err := DoGetBytesRaw(url)
if err != nil {
	return nil, err
}

var user *User
err = json.Unmarshal(bytes, &user)
```
encounters this.

By the way I noticed that actually `DoGetBytesRaw()` already unmarshaled response bytes to standard response data modal and then return the original reponse bytes. Maybe changing this would help.
```go
// DoGetBytesRaw is a general function to get response from param url through HTTP Get method.
func DoGetBytesRaw(url string) ([]byte, error) {
	respBytes, err := doGetBytesRawWithoutCheck(url)
	if err != nil {
		return nil, err
	}

	var response Response
	err = json.Unmarshal(respBytes, &response)
	if err == nil && response.Status == "error"{
		return nil, errors.New(response.Msg)
	}

	return respBytes, nil
}
```

Maybe more sdks like java-sdk, js-sdk or rust-sdk also have this issue, are the next steps of  https://github.com/casdoor/casdoor/commit/a6f803aff1e634ae92b669975baa366a6b3b39c8 underway?

**Comment by hsluoyz** [comment]
@WinterOfBit yes, all SDKs need to be updated after PR: https://github.com/casdoor/casdoor/pull/2111 is merged. Can you update the Go SDK?

**Comment by WinterOfBit** [comment]
> @WinterOfBit yes, all SDKs need to be updated after PR: [casdoor/casdoor#2111](https://github.com/casdoor/casdoor/pull/2111) is merged. Can you update the Go SDK?

Ok. working on this now.

**Comment by hsluoyz** [comment]
@WinterOfBit the PR: https://github.com/casdoor/casdoor/pull/2111 was already merged. Can you proceed with this issue now?

**Comment by WinterOfBit** [comment]
> @WinterOfBit the PR: [casdoor/casdoor#2111](https://github.com/casdoor/casdoor/pull/2111) was already merged. Can you proceed with this issue now?

@hsluoyz #73 altered all usages of base.go#DoGetBytesRaw() with base.go#DoGetBytes(), which seems to have solved this issue. Am I missing any APIs?

**Comment by hsluoyz** [comment]
@WinterOfBit ok, then plz close this issue if resolved
