### ISSUE TITLE
Should go sdk provide a NewClient Function and be OOP?

### ISSUE THREAD

**Issue by WinterOfBit** [casdoor/casdoor-go-sdk#74]
For instance, aliyun oss sdk and [gitea go sdk](https://pkg.go.dev/code.gitea.io/sdk/gitea#Client) both are OOP, which provide a `Client` struct and support a `NewClient` func. This enables them to support multiple sdk clients with different conf exist in the same time.

Can casdoor support `Client` concept and enable sdk users to connect to multiple casdoor server in the same time?

Example function demand source:  https://github.com/casbin/casibase/pull/594#discussion_r1271304392

**Comment by hsluoyz** [comment]
@WinterOfBit good idea. Can you make a PR to support it?

**Comment by WinterOfBit** [comment]
> @WinterOfBit good idea. Can you make a PR to support it?

@hsluoyz No problem. That would be quite a big api change. But should the original `InitConfig` func and functions depends on the global config vars be removed or remain as is for now?

**Comment by hsluoyz** [comment]
@WinterOfBit keep the old usage, both global and client ways can be supported at the same time
