### ISSUE TITLE
How can I get the code and state from casdoor?

### ISSUE THREAD

**Issue by Dav1dch** [casdoor/casdoor-go-sdk#8]
How can I get the code and state from casdoor?

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo

**Comment by Kininaru** [comment]
Do you mean the `code` and `state` in callback redirections?

`code` is generated by Casdoor backend and `state` is the application name.

By the way, you do not need to get `code` and `state`... Casdoor and its SDK will deal with those things...

**Comment by Dav1dch** [comment]
Thanks! I have settled it.

**Comment by tetra12** [comment]
Hello @Dav1dch 

How did you get the code ? I'm following [this](https://casdoor.org/docs/how-to-connect/access_token), but can't make it work. 
Here's what I did

1. Ran a local server with the casdoor-all-in-one
2. Created an organization
3. Created an app
4. Created a user 
5. Then I do the following
```bash
http://127.0.0.1:8000/api/login/oauth/code&client_id=4fd47f868b2e68aa715e&redirect_uri=http%3A%2F%2Flocalhost:9000&response_type=code&scope=openid&state=app_sdk_back
```
and got the following response:
```
{
  "status": "error",
  "msg": "Unauthorized operation",
  "data": null,
  "data2": null
}
```

UPD:

I also tried to run `curl` for resource owner password and client credentials, like this:
client.json
```
{
  "grant_type": "client_credentials",
  "client_id": "4fd47f868b2e68aa715e",
  "client_secret": "61b789afdeb66f8ba6ff8037837ac29a1a61bb6a"
}
```
`curl -v -d client.json 127.0.0.1:8000/api/login/oauth/access_token` , but still getting this:
OK 200
```
{
  "access_token": "error: invalid client_id",
  "id_token": "",
  "refresh_token": "",
  "token_type": "",
  "expires_in": 0,
  "scope": ""
* Connection #0 to host 127.0.0.1 left intact
}%   
```

Could you pls give a hint how to resolve this? Thanks !

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by tetra12** [comment]
@hsluoyz @Steve0x2a Hi guys

Thanks for a prompt fix. That indeed resolved my first issue and allowed me to get the oidc code. 

However, I'm still not able to get an `access_token` by any way described [here](https://casdoor.org/docs/how-to-connect/access_token).

Here's my situation 
1. I'm running `casdoor-all-in-one` locally
2. I don't have a front end (yet). Just wanna get an access and refresh tokens
3. Followed your updated docs. Got the following redirection in browser : `http://localhost:9000/callback?code=60f946be41dccd4902a4&state=app-sdk-back`
4. Trying to get an `access_token` with:

authCode.json

```json
{
  "grant_type": "authorization_code",
  "client_id": "4fd47f868b2e68aa715e",
  "client_secret": "61b789afdeb66f8ba6ff8037837ac29a1a61bb6a",
  "code": "60f946be41dccd4902a4"
}
```

`curl -v -d authCode.json 127.0.0.1:8000/api/login/oauth/access_token`
and still getting the response:
```bash
*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> POST /api/login/oauth/access_token HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 13 out of 13 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 143
< Content-Type: application/json; charset=utf-8
< Server: beegoServer:1.12.3
< Set-Cookie: casdoor_session_id=d0f5cab7ebf6cbe2390201deb897b7aa; Path=/; Expires=Sat, 30 Apr 2022 10:26:53 GMT; Max-Age=2592000; HttpOnly
< Date: Thu, 31 Mar 2022 10:26:53 GMT
< 
{
  "access_token": "error: invalid client_id",
  "id_token": "",
  "refresh_token": "",
  "token_type": "",
  "expires_in": 0,
  "scope": ""
* Connection #0 to host 127.0.0.1 left intact
}%  
```

I double checked `client ID` and `client secret` in the Casdoor GUI. Any advice ?

**Comment by Steve0x2a** [comment]
@Dav1dch I tried to get the token with the following code and it worked, you can try it and give feedback, I will keep following up.
```bash
curl  'http://localhost:8000/api/login/oauth/access_token' -d 'grant_type=authorization_code&client_id=c58c570b63c9bdbfe00c&client_secret=deabbc5717262b162c2b7235bc32496b05549e87&code=4aa380be817bd35ca289'
```

**Comment by Steve0x2a** [comment]
Alternatively, if your application is without a front-end, you might want to consider the Client Credentials Grant and the Resource Owner Password Credentials Grant in OAuth, both of which support obtaining tokens without a front-end (but with slightly less security). Casdoor has full support for both of these, see the [documentation](https://casdoor.org/docs/how-to-connect/access_token#resource-owner-password-credentials-grant).

**Comment by tetra12** [comment]
This wont' work. I opened an issue https://github.com/casdoor/casdoor/issues/635 since I can't get a token with the Resource owner password credentials. Both `grant_type == password` and `grant_type == client_credentials` won't work for me

**Comment by waffle-frame** [comment]
Hello
How can I get an access token using the [Resource Owner Password Credentials Grant](https://casdoor.org/ru/docs/how-to-connect/oauth/#resource-owner-password-credentials-grant) method via casdoorsdk?

While examining the casador authorization functional code, I did not find this method. The GetOAuthToken method only accepts 2 values, which are not related to the above method.

![image](https://github.com/casdoor/casdoor-go-sdk/assets/113475097/e0f78e4e-12c4-41aa-b75b-50e51b614fe6)

**Comment by hsluoyz** [comment]
@Dav1dch don't ask question in an issue 3 years ago
