### ISSUE TITLE
function GetUserByPhone always error "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by tlthanh** [casdoor/casdoor-go-sdk#89]
I can't use this function, it always gives the error "invalid character '<' looking for beginning of value"

**Comment by hsluoyz** [comment]
@tlthanh provider a curl example for demo site: https://door.casdoor.com/

**Comment by hsluoyz** [comment]
@tlthanh tested and it has no issue

![image](https://github.com/casdoor/casdoor-go-sdk/assets/3787410/139345b1-656d-4136-af45-7d64fbcec92a)

**Comment by maknahar** [comment]
I am getting the same issue while using `GetUserByUserId` API. @tlthanh Did you figure out the root cause of the issue by any chance?

**Comment by hsluoyz** [comment]
@tlthanh @maknahar fixed by: https://github.com/casdoor/casdoor/commit/cb200687dce15aa5723928b98c1df3353ca9b1af
