### ISSUE TITLE
[Feature Needed] Add /get-token?id=? support

### ISSUE THREAD

**Issue by geek981108** [casdoor/casdoor-go-sdk#94]
Casdoor has a token api which receive ``` id ``` parameter to get token detail. 

And no implementation of the api was found in casdoor-go-sdk.

![image](https://github.com/casdoor/casdoor-go-sdk/assets/28996049/4a0d636b-e86d-4e16-b0e4-56a10c24bf8d)

**Comment by hsluoyz** [comment]
fixed by: https://github.com/casdoor/casdoor-go-sdk/commit/348c6d99dc24fd6f66e39ced23e41137715c7765
