### ISSUE TITLE
Refresh token and access token are interchangeable

### ISSUE THREAD

**Issue by pi-kei** [casdoor/casdoor-go-sdk#99]
Version: 0.35.1

If you pass either refresh token or access token to `casdoorsdk.ParseJwtToken(token)` then token will pass verification and there's no good way to distinct one from another using returned `casdoorsdk.Claims`. The downside of this is that security risks are higher.

You can use jwt parser directly without casdoor sdk to ensure token type. Refresh tokens have a claim `TokenType` that equal to `refresh-token`

**Comment by hsluoyz** [comment]
@pi-kei Casdoor's refresh token and access token are very similar, this is by design. You can check `refreshClaims["TokenType"] = "refresh-token"` by yourself to see if it is a refresh token

![image](https://github.com/casdoor/casdoor-go-sdk/assets/3787410/6c25bad0-a61f-4afd-8f1c-75ec72b5cd80)

**Comment by pi-kei** [comment]
@hsluoyz To make it clear: Does it make sense to add the claim `TokenType` to `casdoorsdk.Claims`?

**Comment by hsluoyz** [comment]
@pi-kei isn't it already there? See:

![image](https://github.com/casdoor/casdoor-go-sdk/assets/3787410/e1e1d38c-ba86-4140-afee-d7542e6d9576)

**Comment by hsluoyz** [comment]
@pi-kei didn't you see that the value is already set in the claims before generating the JWT?

![image](https://github.com/casdoor/casdoor-go-sdk/assets/3787410/1700dbdf-796a-49c0-9290-a99e2a566652)

**Comment by pi-kei** [comment]
@hsluoyz Yes, I see that the value is already set in the claims before generating the JWT. I even write about that when I created this issue. 
I am talking about github.com/casdoor/casdoor-go-sdk/casdoorsdk package and it's usecases. How can I use this package to get TokenType claim from JWT? Using this package I can get every other claim from JWT except TokenType.

**Comment by hsluoyz** [comment]
@pi-kei if you use: https://jwt.io/ to parse the token, is TokenType there already?

**Comment by pi-kei** [comment]
@hsluoyz Yes, it is there. But the question is how to get it in the code using this sdk package. And the answer is I can't until it will be modified. Should it be modified?

**Comment by hsluoyz** [comment]
@pi-kei yes, can you make a PR?

**Comment by pi-kei** [comment]
@hsluoyz Sure.
